version: "3.6"
services:
  # Wordpress auto configuration
  # depends on wp-cli build
  wp-auto-config:
    image: wpcli
    build: ./wpcli/
    container_name: ${COMPOSE_PROJECT_NAME}-wp-autoconfig
    entrypoint: sh -c "/wait && make -f /scripts/Makefile"
    volumes:
      - ${WORDPRESS_LOCAL_DIR}:${WORDPRESS_CONTAINER_DIR}
      - ${WORDPRESS_THEME_LOCAL_DIR}:${WORDPRESS_THEME_CONTAINER_ROOT_DIR}
      - ${WORDPRESS_THEME_PLUGIN_LOCAL_DIR}:${WORDPRESS_THEME_PLUGIN_CONTAINER_ROOT_DIR}
    working_dir: ${WORDPRESS_CONTAINER_DIR}
    depends_on:
      - wordpress
      - mariadb
    environment:
      # Waiting for Mariadb and wordpress -------------------
      - WAIT_HOSTS=mariadb:3306,wordpress:80
      - WAIT_BEFORE_HOSTS=${WAIT_BEFORE_HOSTS:-30}
      - WAIT_AFTER_HOSTS=${WAIT_AFTER_HOSTS:-15}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT:-300}
      - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL:-30}
      - WAIT_HOST_CONNECT_TIMEOUT=${WAIT_HOST_CONNECT_TIMEOUT:-30}
      # Wordpress configuration -----------------------------
      - WORDPRESS_LOCALE=${WORDPRESS_LOCALE:-en_US}
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_HOST=${COMPOSE_PROJECT_NAME}-mariadb
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_WEBSITE_TITLE=${WORDPRESS_WEBSITE_TITLE}
      - WORDPRESS_WEBSITE_URL=${WORDPRESS_WEBSITE_URL}
      - WORDPRESS_WEBSITE_URL_WITHOUT_HTTP=${WORDPRESS_WEBSITE_URL}
      - WORDPRESS_WEBSITE_POST_URL_STRUCTURE=${WORDPRESS_WEBSITE_POST_URL_STRUCTURE}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_LOCAL_THEMES=${WORDPRESS_LOCAL_THEMES}
      - WORDPRESS_REPO_THEMES=${WORDPRESS_REPO_THEMES}
      - WORDPRESS_DEFAULT_THEMES=${WORDPRESS_DEFAULT_THEMES}
      - WORDPRESS_LOCAL_PLUGINS=${WORDPRESS_LOCAL_PLUGINS}
      - WORDPRESS_REPO_PLUGINS=${WORDPRESS_REPO_PLUGINS}
      - WORDPRESS_DEFAULT_PLUGINS=${WORDPRESS_DEFAULT_PLUGINS}
      - WORDPRESS_DEFAULT_POSTS_PAGES=${WORDPRESS_DEFAULT_POSTS_PAGES}
      - WORDPRESS_THEME_FOLDER=${WORDPRESS_THEME_FOLDER}
      - WORDPRESS_THEME_PLUGIN_FOLDER=${WORDPRESS_THEME_PLUGIN_FOLDER}
    networks:
      - backend

networks:
  backend:
